name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Test
        run: go test -v ./...
        env:
          JWCH_USERNAME: ${{ secrets.USERNAME_23 }}
          JWCH_PASSWORD: ${{ secrets.PASSWORD_23 }}
